### 1. Numpy

In [11]:
import numpy as np
import scipy.stats as sps

In [3]:
#1. оъединение матриц

A = [1,2,3,4,5,6]
B = [11,12,13,14,15,16]
C = np.hstack((A,B))
print(C)

[ 1  2  3  4  5  6 11 12 13 14 15 16]


In [4]:
#2. Массив элементов

m = np.arange(0, 100).reshape((10, 10))
print(m)
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

m[a, b]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


array([ 9, 18, 27, 36, 45, 54, 63, 72, 81, 90])

In [5]:
#3. След + ненулевые элементы

m = np.array([[1, 2, 1, 5, 0], 
              [1, 5, 4, 12, 2], 
              [2, 3, 0, 6, 0], 
              [2, 0, 0, 1, 5], 
              [7, 2, 1, 9, 0]])
print(m)
print(np.trace(m))   
np.count_nonzero(np.diag(m))

[[ 1  2  1  5  0]
 [ 1  5  4 12  2]
 [ 2  3  0  6  0]
 [ 2  0  0  1  5]
 [ 7  2  1  9  0]]
7


3

In [10]:
#4. Тензоры
a = np.array([[[10, 11, 12, 13],
              [14, 11, 16, 17],
              [18, 19, 20, 21]],
             [[22, 23, 24, 25],
              [26, 12, 28, 10],
              [30, 30, 32, 33]],
             [[34, 35, 36, 37],
              [38, 45, 11, 41],
              [11, 11, 12, 45]]])
values, counts = np.unique(a, return_counts=True)
print(values)
print(counts)

[10 11 12 13 14 16 17 18 19 20 21 22 23 24 25 26 28 30 32 33 34 35 36 37
 38 41 45]
[2 5 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 2]


In [11]:
#5. Замена нулями

a = np.array([[3, -8, 6, 5], 
              [6, 1, -4, -2], 
              [11, -3, -2, -2]])
b = np.array([[4, 2, 31, 6], 
              [-3, 5, 2, -3], 
              [0, 0, 0, 0]])

b[a < 0] = 0
print(b)

[[ 4  0 31  6]
 [-3  5  0  0]
 [ 0  0  0  0]]


In [20]:
#6. Среднее + корень
a = sps.norm.rvs(size = (4,3))
print(a)
a -= np.mean(a, axis = 0)
print(a)

[[ 0.14247375  0.12979346  0.21718127]
 [-0.98749343 -1.11363218 -0.87282015]
 [-0.0900873  -0.4212952   1.18137776]
 [ 0.36916791 -1.55417228  0.47576959]]
[[ 0.28395852  0.86962001 -0.03319585]
 [-0.84600867 -0.37380563 -1.12319727]
 [ 0.05139747  0.31853135  0.93100065]
 [ 0.51065268 -0.81434573  0.22539247]]


In [24]:
#7. Скалярное произведение

In [ ]:
#8. График